num1 = int(input("첫 번째 숫자를 입력하세요 "))
num2 = int(input("두 번째 숫자를 입력하세요 "))
num3 = int(input("세 번째 숫자를 입력하세요 "))
print("덧셈의 결과 : ", num1, " + ", num2, " + ", num3, " = ", num1 + num2 + num3)
print("곱셈의 결과 : ", num1, " * ", num2, " * ", num3, " = ", num1 * num2 * num3)